language: objective-c
osx_image: xcode8.3

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.3'
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=10.3.1'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.3'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=10.3.1'

cache: cocoapods

podfile: Example/Podfile

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild test -destination "$DESTINATION" -workspace Example/NSURLSession-Mock.xcworkspace -scheme NSURLSession-Mock-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
